# Please only mention the non-default settings here:

artifact_infos:
  [
    {
      "name": "embedded_restricted",
      "description": "embedded_restricted",
      "resource_classes":
        {
          "SampleFile":
            {
              "name": "SampleFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "SampleFile",
                  "identifier_slot": "accession",
                  "root_slot": "sample_files",
                },
              "json_schema": {},
            },
          "ExperimentFile":
            {
              "name": "ExperimentFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "ExperimentFile",
                  "identifier_slot": "accession",
                  "root_slot": "experiment_files",
                },
              "json_schema": {},
            },
          "Dataset":
            {
              "name": "Dataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "Dataset",
                  "identifier_slot": "accession",
                  "root_slot": "datasets",
                },
              "json_schema": {},
            },
          "Experiment":
            {
              "name": "Experiment",
              "description": "An experiment containing one or multiple samples.",
              "anchor_point":
                {
                  "target_class": "Experiment",
                  "identifier_slot": "accession",
                  "root_slot": "experiments",
                },
              "json_schema": {},
            },
          "EmbeddedDataset":
            {
              "name": "EmbeddedDataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "EmbeddedDataset",
                  "identifier_slot": "accession",
                  "root_slot": "embedded_dataset",
                },
              "json_schema": {},
            },
          "Sample":
            {
              "name": "Sample",
              "description": "A sample that was used to generate Files containing experiment data.",
              "anchor_point":
                {
                  "target_class": "Sample",
                  "identifier_slot": "accession",
                  "root_slot": "samples",
                },
              "json_schema": {},
            },
        },
    },
    {
      "name": "resolved_restricted",
      "description": "resolved_restricted",
      "resource_classes":
        {
          "SampleFile":
            {
              "name": "SampleFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "SampleFile",
                  "identifier_slot": "accession",
                  "root_slot": "sample_files",
                },
              "json_schema": {},
            },
          "ExperimentFile":
            {
              "name": "ExperimentFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "ExperimentFile",
                  "identifier_slot": "accession",
                  "root_slot": "experiment_files",
                },
              "json_schema": {},
            },
          "Dataset":
            {
              "name": "Dataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "Dataset",
                  "identifier_slot": "accession",
                  "root_slot": "datasets",
                },
              "json_schema": {},
            },
          "Experiment":
            {
              "name": "Experiment",
              "description": "An experiment containing one or multiple samples.",
              "anchor_point":
                {
                  "target_class": "Experiment",
                  "identifier_slot": "accession",
                  "root_slot": "experiments",
                },
              "json_schema": {},
            },
          "Sample":
            {
              "name": "Sample",
              "description": "A sample that was used to generate Files containing experiment data.",
              "anchor_point":
                {
                  "target_class": "Sample",
                  "identifier_slot": "accession",
                  "root_slot": "samples",
                },
              "json_schema": {},
            },
        },
    },
    {
      "name": "resolved_public",
      "description": "resolved_public",
      "resource_classes":
        {
          "SampleFile":
            {
              "name": "SampleFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "SampleFile",
                  "identifier_slot": "accession",
                  "root_slot": "sample_files",
                },
              "json_schema": {},
            },
          "ExperimentFile":
            {
              "name": "ExperimentFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "ExperimentFile",
                  "identifier_slot": "accession",
                  "root_slot": "experiment_files",
                },
              "json_schema": {},
            },
          "Dataset":
            {
              "name": "Dataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "Dataset",
                  "identifier_slot": "accession",
                  "root_slot": "datasets",
                },
              "json_schema": {},
            },
          "Experiment":
            {
              "name": "Experiment",
              "description": "An experiment containing one or multiple samples.",
              "anchor_point":
                {
                  "target_class": "Experiment",
                  "identifier_slot": "accession",
                  "root_slot": "experiments",
                },
              "json_schema": {},
            },
          "Sample":
            {
              "name": "Sample",
              "description": "A sample that was used to generate Files containing experiment data.",
              "anchor_point":
                {
                  "target_class": "Sample",
                  "identifier_slot": "accession",
                  "root_slot": "samples",
                },
              "json_schema": {},
            },
        },
    },
    {
      "name": "embedded_public",
      "description": "embedded_public",
      "resource_classes":
        {
          "SampleFile":
            {
              "name": "SampleFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "SampleFile",
                  "identifier_slot": "accession",
                  "root_slot": "sample_files",
                },
              "json_schema": {},
            },
          "ExperimentFile":
            {
              "name": "ExperimentFile",
              "description": null,
              "anchor_point":
                {
                  "target_class": "ExperimentFile",
                  "identifier_slot": "accession",
                  "root_slot": "experiment_files",
                },
              "json_schema": {},
            },
          "Dataset":
            {
              "name": "Dataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "Dataset",
                  "identifier_slot": "accession",
                  "root_slot": "datasets",
                },
              "json_schema": {},
            },
          "Experiment":
            {
              "name": "Experiment",
              "description": "An experiment containing one or multiple samples.",
              "anchor_point":
                {
                  "target_class": "Experiment",
                  "identifier_slot": "accession",
                  "root_slot": "experiments",
                },
              "json_schema": {},
            },
          "EmbeddedDataset":
            {
              "name": "EmbeddedDataset",
              "description": "A Dataset is a collection of Files.",
              "anchor_point":
                {
                  "target_class": "EmbeddedDataset",
                  "identifier_slot": "accession",
                  "root_slot": "embedded_dataset",
                },
              "json_schema": {},
            },
          "Sample":
            {
              "name": "Sample",
              "description": "A sample that was used to generate Files containing experiment data.",
              "anchor_point":
                {
                  "target_class": "Sample",
                  "identifier_slot": "accession",
                  "root_slot": "samples",
                },
              "json_schema": {},
            },
        },
    },
  ]
db_connection_str: "mongodb://mongodb:27017"
db_name: dev_db
loader_token_hashes:
  ["09e5724dab34b50fe2db5ebae7ac5eac4ef2904d105f8f2b3d5a4cb2c7f43da4"]
log_level: trace
