[project]
name = "ghga_datasteward_kit"
version = "4.8.0"
description = "GHGA Data Steward Kit - A utils package for GHGA data stewards."
dependencies = [
    "crypt4gh >=1.6, <2",
    "hexkit[s3] >=5.1",
    "ghga-transpiler >=2.1.2, <3",
    "metldata~=3.0.3",
    "tenacity >=9.0.0, <10",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-datasteward-kit"

[project.scripts]
ghga-datasteward-kit = "ghga_datasteward_kit.__main__:run"
