[project]
name = "ghga_datasteward_kit"
version = "2.1.0"
description = "GHGA Data Steward Kit - A utils package for GHGA data stewards."
dependencies = [
    "crypt4gh >=1.6, <2",
    "hexkit[s3] >=3, <4",
    "ghga-transpiler >=2.1, <3",
    "metldata~=1.3.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-datasteward-kit"

[project.scripts]
ghga-datasteward-kit = "ghga_datasteward_kit.__main__:run"
