name: CI on release

on:
  release:
      types: [published]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - uses: ghga-de/gh-action-ci@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
