name: PyPI Publish

on:
  push: {}

jobs:
  pypi-publish:
    name: Publish tagged release on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Install the newly build package with all extras
        run: |
          TAR_PATH="$( realpath ./dist/*.tar.gz)"
          python3 -m \
            pip install \
            "${TAR_PATH}[all]"

      - name: Run pytest on freshly install package
        run: |
          pytest .
