name: PyPI Publish

on:
  push: {}

jobs:
  pypi-publish:
    name: Publish tagged release on PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.9

      - name: Verify Package Version vs Tag Version
        run: |
          PKG_VER="$(python setup.py -V)"
          TAG_VER="${GITHUB_REF##*/}"
          echo "Package version is $PKG_VER" >&2
          echo "Tag version is $TAG_VER" >&2
          if [ "$PKG_VER" != "$TAG_VER" ]; then
            echo "Package version and tag name mismatch." >&2
            exit 1
          fi

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Install the newly build package with all extras
        run: |
          TAR_PATH="$( realpath ./dist/*.tar.gz)"
          python3 -m \
            pip install \
            "${TAR_PATH}[all]"

      - name: Run pytest on freshly install package
        run: |
          pytest .
