name: Run test suite and measure coverage

on: push

jobs:
  tests:
    name: Run test suite

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6

      - name: Run tests
        id: pytest
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          pytest \
            --cov="${{ steps.common.outputs.PACKAGE_NAME }}" \
            --cov-report=xml \
            tests

      - name: Upload coverage to coveralls
        id: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade coveralls
          coveralls --service=github
